# To use:
#
#   $ micromamba create -f environment.yml  # `micromamba` works too for this command
#   $ micromamba activate readcon_dev
#
name: potlibR_dev
channels:
  - conda-forge
dependencies:
  - compilers
  - clang
  - meson
  - ninja
  - cmake
  - pkg-config
  - r-cpp11
  # For the R bindings
  # - r-rcpp
  # - r-rcppeigen
  - r-devtools
  # For linting
  - r-styler
  - r-lintr
  - r-codemeta
  # Interactive R
  - radian
