# To use:
#
#   $ micromamba create -f environment.yml  # `micromamba` works too for this command
#   $ micromamba activate readcon_dev
#
name: potlibR_dev
channels:
  - conda-forge
dependencies:
  - compilers
  - clang
  - meson
  - ninja
  - cmake
  - pkg-config
  # Potlib dep
  - openblas
  - gfortran
  # (pinned)
  - eigen==3.4.0
  # (libs)
  - fmt
  - spdlog
  # For the R bindings
  - r-cpp11
  - r-devtools
  # For linting
  - r-styler
  - r-lintr
  - r-codemeta
  # Interactive R
  - radian
