// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
cpp11::writable::doubles cuh2pot(cpp11::data_frame df);
extern "C" SEXP _potlibR_cuh2pot(SEXP df) {
  BEGIN_CPP11
    return cpp11::as_sexp(cuh2pot(cpp11::as_cpp<cpp11::decay_t<cpp11::data_frame>>(df)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_potlibR_cuh2pot", (DL_FUNC) &_potlibR_cuh2pot, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_potlibR(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
